"""Refactor models

Revision ID: 66659bc51752
Revises: e2847933735c
Create Date: 2025-02-17 03:18:15.940066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66659bc51752'
down_revision: Union[str, None] = 'e2847933735c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_items_name', table_name='items')
    op.create_index(op.f('ix_public_items_name'), 'items', ['name'], unique=False, schema='public')
    op.drop_constraint('purchases_item_id_fkey', 'purchases', type_='foreignkey')
    op.drop_constraint('purchases_user_id_fkey', 'purchases', type_='foreignkey')
    op.create_foreign_key(None, 'purchases', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'purchases', 'items', ['item_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('transactions_from_user_id_fkey', 'transactions', type_='foreignkey')
    op.drop_constraint('transactions_to_user_id_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'users', ['to_user_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'transactions', 'users', ['from_user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_public_users_username'), 'users', ['username'], unique=True, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_users_username'), table_name='users', schema='public')
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.drop_constraint(None, 'transactions', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'transactions', schema='public', type_='foreignkey')
    op.create_foreign_key('transactions_to_user_id_fkey', 'transactions', 'users', ['to_user_id'], ['id'])
    op.create_foreign_key('transactions_from_user_id_fkey', 'transactions', 'users', ['from_user_id'], ['id'])
    op.drop_constraint(None, 'purchases', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'purchases', schema='public', type_='foreignkey')
    op.create_foreign_key('purchases_user_id_fkey', 'purchases', 'users', ['user_id'], ['id'])
    op.create_foreign_key('purchases_item_id_fkey', 'purchases', 'items', ['item_id'], ['id'])
    op.drop_index(op.f('ix_public_items_name'), table_name='items', schema='public')
    op.create_index('ix_items_name', 'items', ['name'], unique=False)
    # ### end Alembic commands ###
